events {
    worker_connections 1024;
}

http {
    upstream company_scraper {
        server company-scraper:5000;
    }

    server {
        listen 80;
        server_name companycheck.wearefum.web.id;

        location / {
            proxy_pass http://company_scraper;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}